name: Publish Basics

on: 
  release:
    types: [ created ]


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint-ci
      - run: npm run build
      # Note: Currently only publishing to NPM since GitHub does not allow unauthenticated access to public packages!
      - name: Setup node for NPMjs Packages
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to NPMjs Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
